version: 2.1
working_directory: ~/repo
executors:
  nodeBuilder:
    docker:
      - image: circleci/node:14
jobs:
  executor: nodeBuilder
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm build
  test:
    steps:
      - run: npm test


