version: 2.1
working_directory: ~/repo
orbs:
  docker:
    - image: circleci/node:14
jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm build
  test:
    steps:
      - run: npm test


